export const TEST_ACTION = 'TEST_ACTION';
//Snippets
export const GET_001_INSTALL_REACT = 'GET_001_INSTALL_REACT';
export const GET_002_INSTALL_REACT_ROUTER = 'GET_002_INSTALL_REACT_ROUTER';
export const GET_003_CREATE_BACKEND_SERVER = 'GET_003_CREATE_BACKEND_SERVER';

export const GET_005_CONNECT_DB_TO_SERVER = 'GET_005_CONNECT_DB_TO_SERVER';
export const GET_006_ROUTING_WITH_EXPRESS_ROUTER = 'GET_006_ROUTING_WITH_EXPRESS_ROUTER';
export const GET_007__CREATE_DB_MODEL = 'GET_007__CREATE_DB_MODEL';
export const GET_008_A_BACKEND_ROUTES_PART_I = 'GET_008_A_BACKEND_ROUTES_PART_I';
export const GET_008_B_BACKEND_ROUTES_PART_II_LOGIN = "GET_008_B_BACKEND_ROUTES_PART_II_LOGIN";
export const GET_008_C_BACKEND_ROUTES_PART_III_TOKEN = 'GET_008_C_BACKEND_ROUTES_PART_III_TOKEN';
export const GET_008_D_BACKEND_ROUTES_PART_IV_PASSPORT = 'GET_008_D_BACKEND_ROUTES_PART_IV_PASSPORT';

export const GET_009_SET_UP_REDUX = 'GET_009_SET_UP_REDUX';
export const GET_010_REDUX_REACT_ACTIONS = 'GET_010_REDUX_REACT_ACTIONS';

//API SECTIONS
export const GET_SNIPPETS_001_AJAX_AND_API_BASIC_API_CALLS = 'GET_SNIPPETS_001_AJAX_AND_API_BASIC_API_CALLS';



//  ====    Images  ====

//FullStack Sections
export const GET_IMAGES_001_INSTALL_REACT = 'GET_IMAGES_001_INSTALL_REACT';
export const GET_IMAGES_002_INSTALL_REACT_ROUTER = 'GET_IMAGES_002_INSTALL_REACT_ROUTER';
export const GET_IMAGES_003_CREATE_BACKEND = 'GET_IMAGES_003_CREATE_BACKEND';
export const GET_IMAGES_004_MLAB_SETUP = 'GET_IMAGES_004_MLAB_SETUP';
export const GET_IMAGES_005_CONNECT_DB_TO_SERVER = 'GET_IMAGES_005_CONNECT_DB_TO_SERVER';
export const GET_IMAGES_006_ROUTING_EXPRESS_ROUTER = 'GET_IMAGES_006_ROUTING_EXPRESS_ROUTER';
export const GET_IMAGES_007_CREATE_DB_MODEL = 'GET_IMAGES_007_CREATE_DB_MODEL';
export const GET_IMAGES_008_POSTMAN = 'GET_IMAGES_008_POSTMAN';
export const GET_IMAGES_008_A_BACKEND_ROUTES_PART_I = 'GET_IMAGES_008_A_BACKEND_ROUTES_PART_I';
export const GET_IMAGES_008_B_BACKEND_ROUTES_PART_II = 'GET_IMAGES_008_B_BACKEND_ROUTES_PART_II';
export const GET_IMAGES_008_C_BACKEND_ROUTES_PART_III = 'GET_IMAGES_008_C_BACKEND_ROUTES_PART_III';
export const GET_IMAGES_008_D_BACKEND_ROUTES_PART_IV = 'GET_IMAGES_008_D_BACKEND_ROUTES_PART_IV';

//API Sections
export const GET_IMAGES_001_AJAX_AND_API_BASIC_API_CALLS = 'GET_IMAGES_001_AJAX_AND_API_BASIC_API_CALLS';




export const GET_IMAGES_009_SETUP_REDUX = 'GET_IMAGES_009_SETUP_REDUX';
export const GET_IMAGES_010_REDUX_REACT_ACTIONS = 'GET_IMAGES_010_REDUX_REACT_ACTIONS';


//Nav Actions
export const GET_MOBILE_NAV_SECTIONS = 'GET_MOBILE_NAV_SECTIONS';
export const GET_SIDE_NAV_SECTION_LINKS = 'GET_SIDE_NAV_SECTION_LINKS';
export const GET_CURRENT_MOBILE_SECTIONS_ON_CLICK = 'GET_CURRENT_MOBILE_SECTIONS_ON_CLICK';


//  ====    TEXT  ====

//API SECTIONS
export const GET_TEXT_001_AJAX_AND_API_BASIC_API_CALLS = 'GET_TEXT_001_AJAX_AND_API_BASIC_API_CALLS';

//FULL STACK SECTIONS
export const GET_TEXT_008_A_BACKEND_ROUTES_PART_I = 'GET_TEXT_008_A_BACKEND_ROUTES_PART_I'
export const GET_TEXT_008_B_BACKEND_ROUTES_PART_II_LOGIN = 'GET_TEXT_008_B_BACKEND_ROUTES_PART_II_LOGIN'
export const GET_TEXT_008_C_BACKEND_ROUTES_PART_III_ISSUE_TOKEN = 'GET_TEXT_008_C_BACKEND_ROUTES_PART_III_ISSUE_TOKEN';
export const GET_TEXT_008_D_BACKEND_ROUTES_PART_IV_ISSUE_TOKEN = 'GET_TEXT_008_D_BACKEND_ROUTES_PART_IV_ISSUE_TOKEN';